version: "3.9"
services:
  bitwarden:
    image: vaultwarden/server:1.29.1-alpine
    container_name: bitwarden
    labels:
      - traefik.enable=true
      # web
      - traefik.http.routers.bitwarden-http.rule=Host(`bitwarden.arm.furysphere.com`)
      - traefik.http.routers.bitwarden-http.entrypoints=web
      - traefik.http.routers.bitwarden-http.middlewares=force-https
      # websecure
      - traefik.http.routers.bitwarden-https.rule=Host(`bitwarden.arm.furysphere.com`)
      - traefik.http.routers.bitwarden-https.entrypoints=websecure
      - traefik.http.services.bitwarden-https.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden-https.tls=true
      - traefik.http.routers.bitwarden-https.tls.certresolver=leprod
    environment:
      ORG_GROUPS_ENABLED: true
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN:
        # ports:
        #   - 80:80
    volumes:
      - bitwarden_data:/data
    networks:
      - internal-net
    restart: unless-stopped
volumes:
  bitwarden_data:
networks:
  internal-net:
    name: internal-net
    external: true
