version: "3.9"
services:
  traefik:
    image: traefik:v2.9.6
    container_name: traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    ports:
      - 80:80
      - 443:443
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_config:/etc/traefik/
    networks:
      - integrella-net
    restart: unless-stopped
volumes:
  traefik_config:
    driver_opts:
      type: none
      o: bind
      device: /Users/chiragshah/Arcane/docker_volumes/traefik/
networks:
  integrella-net:
    name: integrella-net
    external: true
