version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4:6.20
    container_name: pgadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@email.com"
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENABLE_PSQL: "True"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    # ports:
    # - 80:80
    networks:
      - internal-net
volumes:
  pgadmin_data:
    driver_opts:
      type: none
      o: bind
      device: /Users/admin/docker_volumes/pgadmin_data
networks:
  internal-net:
    name: internal-net
    external: true
