version: "3.9"
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins_docker_certs:/certs/client
      - jenkins_data:/var/jenkins_home
    ports:
      - 2376:2376
    networks:
      integrella-net:
    restart: unless-stopped
  jenkins:
    depends_on:
      - jenkins-docker
    image: my-jenkins:latest
    container_name: jenkins
    labels:
      - trafeik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.localhost`)
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
    # ports:
    #   - 8080:8080
    #   - 50000:50000
    networks:
      - integrella-net
    restart: unless-stopped
volumes:
  jenkins_docker_certs:
    name: jenkins_docker_certs
    driver_opts:
      type: none
      o: bind
      device: /Users/chiragshah/Arcane/docker_volumes/jenkins/jenkins_docker_certs
  jenkins_data:
    name: jenkins_data
    driver_opts:
      type: none
      o: bind
      device: /Users/chiragshah/Arcane/docker_volumes/jenkins/jenkins_data
networks:
  integrella-net:
    name: integrella-net
    external: true
