---
version: "3"
services:
  portainer:
    image: portainer/portainer-ce:2.17.0-alpine
    container_name: portainer
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.tls=true
    # ports:
    #   - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal-net
    restart: unless-stopped
volumes:
  portainer_data:
    driver_opts:
      type: none
      o: bind
      device: /Users/admin/docker_volumes/portainer_data
networks:
  internal-net:
    name: internal-net
    external: true
