---
version: "3"
services:
  portainer:
    image: portainer/portainer-ce:2.16.2-alpine
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  portainer_data:
    driver_opts:
      type: none
      o: bind
      device: /Users/admin/docker_volumes/portainer_data
networks:
  internal-net:
    name: internal-net
    external: true
