version: '3.8'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: node_exporter
    pid: host
    # network_mode: host
    ports:
      - 9100:9100
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
        - local
    restart: unless-stopped
    command: 
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
networks:
  local:
    name: local-net
    external: true
