version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.7-alpine
    environment:
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
      - internal-net
    restart: unless-stopped
volumes:
  postgres_data:
    driver_opts:
      type: none
      o: bind
      device: /Users/admin/docker_volumes/postgres_data
networks:
  internal-net:
    name: internal-net
    external: true
