version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.7-alpine
    environment:
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
      - integrella-net
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-U"
        - postgres
      interval: 10s
      timeout: 3s
volumes:
  postgres_data:
    driver_opts:
      type: none
      o: bind
      device: /Users/chiragshah/Arcane/docker_volumes/postgres_data
networks:
  integrella-net:
    name: integrella-net
    external: true
